// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

public enum AxisPartClass : sbyte
{
  NONE = 0,
  WIRE = 1,
  WIRE_SET = 2,
  CIRCLE_CURVE = 3,
};


}
