// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BigShellProfile : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BigShellProfile GetRootAsBigShellProfile(ByteBuffer _bb) { return GetRootAsBigShellProfile(_bb, new BigShellProfile()); }
  public static BigShellProfile GetRootAsBigShellProfile(ByteBuffer _bb, BigShellProfile obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BigShellProfile __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Indices(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(__p.__vector(o) + j * 4) : (uint)0; }
  public int IndicesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<uint> GetIndicesBytes() { return __p.__vector_as_span<uint>(4, 4); }
#else
  public ArraySegment<byte>? GetIndicesBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public uint[] GetIndicesArray() { return __p.__vector_as_array<uint>(4); }

  public static Offset<AnalyseTool.Fragments.Schema.BigShellProfile> CreateBigShellProfile(FlatBufferBuilder builder,
      VectorOffset indicesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    BigShellProfile.AddIndices(builder, indicesOffset);
    return BigShellProfile.EndBigShellProfile(builder);
  }

  public static void StartBigShellProfile(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIndices(FlatBufferBuilder builder, VectorOffset indicesOffset) { builder.AddOffset(0, indicesOffset.Value, 0); }
  public static VectorOffset CreateIndicesVector(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddUint(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, uint[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, ArraySegment<uint> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateIndicesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<uint>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartIndicesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<AnalyseTool.Fragments.Schema.BigShellProfile> EndBigShellProfile(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // indices
    return new Offset<AnalyseTool.Fragments.Schema.BigShellProfile>(o);
  }
}


static public class BigShellProfileVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Indices*/, 4 /*uint*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
