// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct BoundingBox : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public BoundingBox __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public AnalyseTool.Fragments.Schema.FloatVector Min { get { return (new AnalyseTool.Fragments.Schema.FloatVector()).__assign(__p.bb_pos + 0, __p.bb); } }
  public AnalyseTool.Fragments.Schema.FloatVector Max { get { return (new AnalyseTool.Fragments.Schema.FloatVector()).__assign(__p.bb_pos + 12, __p.bb); } }

  public static Offset<AnalyseTool.Fragments.Schema.BoundingBox> CreateBoundingBox(FlatBufferBuilder builder, float min_X, float min_Y, float min_Z, float max_X, float max_Y, float max_Z) {
    builder.Prep(4, 24);
    builder.Prep(4, 12);
    builder.PutFloat(max_Z);
    builder.PutFloat(max_Y);
    builder.PutFloat(max_X);
    builder.Prep(4, 12);
    builder.PutFloat(min_Z);
    builder.PutFloat(min_Y);
    builder.PutFloat(min_X);
    return new Offset<AnalyseTool.Fragments.Schema.BoundingBox>(builder.Offset);
  }
}


}
