// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

public enum RenderedFaces : sbyte
{
  ONE = 0,
  TWO = 1,
};


}
