// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Shell : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Shell GetRootAsShell(ByteBuffer _bb) { return GetRootAsShell(_bb, new Shell()); }
  public static Shell GetRootAsShell(ByteBuffer _bb, Shell obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Shell __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public AnalyseTool.Fragments.Schema.ShellProfile? Profiles(int j) { int o = __p.__offset(4); return o != 0 ? (AnalyseTool.Fragments.Schema.ShellProfile?)(new AnalyseTool.Fragments.Schema.ShellProfile()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ProfilesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
  public AnalyseTool.Fragments.Schema.ShellHole? Holes(int j) { int o = __p.__offset(6); return o != 0 ? (AnalyseTool.Fragments.Schema.ShellHole?)(new AnalyseTool.Fragments.Schema.ShellHole()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int HolesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public AnalyseTool.Fragments.Schema.FloatVector? Points(int j) { int o = __p.__offset(8); return o != 0 ? (AnalyseTool.Fragments.Schema.FloatVector?)(new AnalyseTool.Fragments.Schema.FloatVector()).__assign(__p.__vector(o) + j * 12, __p.bb) : null; }
  public int PointsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public AnalyseTool.Fragments.Schema.BigShellProfile? BigProfiles(int j) { int o = __p.__offset(10); return o != 0 ? (AnalyseTool.Fragments.Schema.BigShellProfile?)(new AnalyseTool.Fragments.Schema.BigShellProfile()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BigProfilesLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public AnalyseTool.Fragments.Schema.BigShellHole? BigHoles(int j) { int o = __p.__offset(12); return o != 0 ? (AnalyseTool.Fragments.Schema.BigShellHole?)(new AnalyseTool.Fragments.Schema.BigShellHole()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int BigHolesLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
  public AnalyseTool.Fragments.Schema.ShellType Type { get { int o = __p.__offset(14); return o != 0 ? (AnalyseTool.Fragments.Schema.ShellType)__p.bb.GetSbyte(o + __p.bb_pos) : AnalyseTool.Fragments.Schema.ShellType.NONE; } }
  public ushort ProfilesFaceIds(int j) { int o = __p.__offset(16); return o != 0 ? __p.bb.GetUshort(__p.__vector(o) + j * 2) : (ushort)0; }
  public int ProfilesFaceIdsLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<ushort> GetProfilesFaceIdsBytes() { return __p.__vector_as_span<ushort>(16, 2); }
#else
  public ArraySegment<byte>? GetProfilesFaceIdsBytes() { return __p.__vector_as_arraysegment(16); }
#endif
  public ushort[] GetProfilesFaceIdsArray() { return __p.__vector_as_array<ushort>(16); }

  public static Offset<AnalyseTool.Fragments.Schema.Shell> CreateShell(FlatBufferBuilder builder,
      VectorOffset profilesOffset = default(VectorOffset),
      VectorOffset holesOffset = default(VectorOffset),
      VectorOffset pointsOffset = default(VectorOffset),
      VectorOffset big_profilesOffset = default(VectorOffset),
      VectorOffset big_holesOffset = default(VectorOffset),
      AnalyseTool.Fragments.Schema.ShellType type = AnalyseTool.Fragments.Schema.ShellType.NONE,
      VectorOffset profiles_face_idsOffset = default(VectorOffset)) {
    builder.StartTable(7);
    Shell.AddProfilesFaceIds(builder, profiles_face_idsOffset);
    Shell.AddBigHoles(builder, big_holesOffset);
    Shell.AddBigProfiles(builder, big_profilesOffset);
    Shell.AddPoints(builder, pointsOffset);
    Shell.AddHoles(builder, holesOffset);
    Shell.AddProfiles(builder, profilesOffset);
    Shell.AddType(builder, type);
    return Shell.EndShell(builder);
  }

  public static void StartShell(FlatBufferBuilder builder) { builder.StartTable(7); }
  public static void AddProfiles(FlatBufferBuilder builder, VectorOffset profilesOffset) { builder.AddOffset(0, profilesOffset.Value, 0); }
  public static VectorOffset CreateProfilesVector(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.ShellProfile>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateProfilesVectorBlock(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.ShellProfile>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProfilesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<AnalyseTool.Fragments.Schema.ShellProfile>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProfilesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<AnalyseTool.Fragments.Schema.ShellProfile>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartProfilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHoles(FlatBufferBuilder builder, VectorOffset holesOffset) { builder.AddOffset(1, holesOffset.Value, 0); }
  public static VectorOffset CreateHolesVector(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.ShellHole>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateHolesVectorBlock(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.ShellHole>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHolesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<AnalyseTool.Fragments.Schema.ShellHole>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateHolesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<AnalyseTool.Fragments.Schema.ShellHole>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartHolesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddPoints(FlatBufferBuilder builder, VectorOffset pointsOffset) { builder.AddOffset(2, pointsOffset.Value, 0); }
  public static void StartPointsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(12, numElems, 4); }
  public static void AddBigProfiles(FlatBufferBuilder builder, VectorOffset bigProfilesOffset) { builder.AddOffset(3, bigProfilesOffset.Value, 0); }
  public static VectorOffset CreateBigProfilesVector(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.BigShellProfile>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBigProfilesVectorBlock(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.BigShellProfile>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBigProfilesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<AnalyseTool.Fragments.Schema.BigShellProfile>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBigProfilesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<AnalyseTool.Fragments.Schema.BigShellProfile>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBigProfilesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBigHoles(FlatBufferBuilder builder, VectorOffset bigHolesOffset) { builder.AddOffset(4, bigHolesOffset.Value, 0); }
  public static VectorOffset CreateBigHolesVector(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.BigShellHole>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateBigHolesVectorBlock(FlatBufferBuilder builder, Offset<AnalyseTool.Fragments.Schema.BigShellHole>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBigHolesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<AnalyseTool.Fragments.Schema.BigShellHole>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateBigHolesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<AnalyseTool.Fragments.Schema.BigShellHole>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartBigHolesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddType(FlatBufferBuilder builder, AnalyseTool.Fragments.Schema.ShellType type) { builder.AddSbyte(5, (sbyte)type, 0); }
  public static void AddProfilesFaceIds(FlatBufferBuilder builder, VectorOffset profilesFaceIdsOffset) { builder.AddOffset(6, profilesFaceIdsOffset.Value, 0); }
  public static VectorOffset CreateProfilesFaceIdsVector(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); for (int i = data.Length - 1; i >= 0; i--) builder.AddUshort(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateProfilesFaceIdsVectorBlock(FlatBufferBuilder builder, ushort[] data) { builder.StartVector(2, data.Length, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProfilesFaceIdsVectorBlock(FlatBufferBuilder builder, ArraySegment<ushort> data) { builder.StartVector(2, data.Count, 2); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateProfilesFaceIdsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<ushort>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartProfilesFaceIdsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(2, numElems, 2); }
  public static Offset<AnalyseTool.Fragments.Schema.Shell> EndShell(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    builder.Required(o, 4);  // profiles
    builder.Required(o, 6);  // holes
    builder.Required(o, 8);  // points
    builder.Required(o, 10);  // big_profiles
    builder.Required(o, 12);  // big_holes
    builder.Required(o, 16);  // profiles_face_ids
    return new Offset<AnalyseTool.Fragments.Schema.Shell>(o);
  }
}


static public class ShellVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Profiles*/, AnalyseTool.Fragments.Schema.ShellProfileVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Holes*/, AnalyseTool.Fragments.Schema.ShellHoleVerify.Verify, true)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Points*/, 12 /*AnalyseTool.Fragments.Schema.FloatVector*/, true)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*BigProfiles*/, AnalyseTool.Fragments.Schema.BigShellProfileVerify.Verify, true)
      && verifier.VerifyVectorOfTables(tablePos, 12 /*BigHoles*/, AnalyseTool.Fragments.Schema.BigShellHoleVerify.Verify, true)
      && verifier.VerifyField(tablePos, 14 /*Type*/, 1 /*AnalyseTool.Fragments.Schema.ShellType*/, 1, false)
      && verifier.VerifyVectorOfData(tablePos, 16 /*ProfilesFaceIds*/, 2 /*ushort*/, true)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
