// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace AnalyseTool.Fragments.Schema
{

public enum Stroke : sbyte
{
  DEFAULT = 0,
};


}
