namespace AnalyseTool.Mcp
{
    /// <summary>
    /// Wire contract of the localhost TCP bridge between the two halves of the MCP subsystem:
    /// AnalyseTool.Mcp.exe (out-of-process, System.Text.Json) and AnalyseTool.Mcp.Bridge
    /// (in-Revit, Newtonsoft). The file is COMPILED INTO BOTH projects (linked in the exe's
    /// csproj), so renaming a field breaks the build instead of silently breaking the wire.
    ///
    /// Shapes:
    ///   request  { id, token, type: "invoke"|"list"|"version"|"cancel"|"result", command?, payload? }
    ///   response { id, result } | { id, error: { code, message, hint? } }
    ///   interim  { id, progress: { fraction, message? } }   — zero or more, BEFORE the response of an
    ///            invoke, on the same connection (#108)
    ///   cancel   { type: "cancel", id: <call id> } on a NEW connection → { result: { cancelled } } (#109)
    ///   result   { type: "result", id: <call id> } → { result: { status, command, seconds, result?, error? } }
    ///            — the stored outcome of a call whose connection is gone (#99);
    ///            { type: "result", list: true } → { result: { jobs: [{ id, status, command, seconds }] } }
    ///            — the recent calls, newest first, for a caller that lost its handle
    ///   list result: { commands: [ { name, source, description, readOnly, destructive,
    ///                                inputSchema, outputSchema } ] }
    ///
    /// The error is an OBJECT so a caller can branch on <c>code</c> instead of matching prose — an agent
    /// deciding between "fix the arguments and retry" and "wait for Revit" should not be doing string
    /// comparison on a sentence that may be reworded. Both halves ship from the same build, so the shape
    /// cannot skew; the reader still accepts a bare string, because tolerating the older form costs one
    /// line and turns a hypothetical mismatch into a readable message rather than a crash.
    ///
    /// Every request carries the session token. Binding to 127.0.0.1 keeps the browser and the network
    /// out, but it does not keep out other processes running as the same user — and this bridge drives
    /// Revit. The token is generated by the host, stored in mcp.json (a user-only file) and handed to
    /// the exe on its command line by the config snippet Settings generates.
    /// </summary>
    internal static class McpWire
    {
        public const int DefaultPort = 17890;

        // Envelope fields
        public const string Id = "id";
        public const string Token = "token";
        public const string Type = "type";
        public const string Command = "command";
        public const string Payload = "payload";
        public const string Result = "result";
        public const string Error = "error";

        // Request types
        public const string TypeInvoke = "invoke";
        public const string TypeList = "list";
        /// <summary>Asks for nothing but the catalog stamp — the cheapest possible request, for a client
        /// polling "did the tool set change while I was not looking".</summary>
        public const string TypeVersion = "version";

        /// <summary>Stamped onto EVERY reply (result and error alike): an opaque string that changes
        /// whenever the set of commands an AI may call changes — extensions reloaded, the C# switch
        /// flipped. The exe compares it with the one it listed under and, on a difference, re-lists and
        /// tells the client (tools/list_changed). It is the only signal that crosses the wire in the
        /// server→client direction, and it rides on replies because the bridge cannot initiate.</summary>
        public const string Catalog = "catalog";

        /// <summary>Stops the call with this id. The bridge holds a CancellationTokenSource per call in
        /// flight; the command sees its token cancelled and the original call answers Codes.Cancelled.
        /// Sent on a connection of its own, because the call's own connection is busy waiting.</summary>
        public const string TypeCancel = "cancel";
        /// <summary>Asks for the stored outcome of an earlier call by its id. The bridge keeps every
        /// invoke's outcome for a while (JobRetention) whether or not anybody was still connected to
        /// receive it — so a client that gave up at four minutes, or a chat the user closed, can still
        /// collect what Revit finished (#99).</summary>
        public const string TypeResult = "result";
        /// <summary>On a "result" request: not one call but the recent ones, newest first. A client whose
        /// own timeout swallowed the handle (a tool call that never returned) has no id to quote — this
        /// is how it finds it.</summary>
        public const string List = "list";
        public const string Jobs = "jobs";
        /// <summary>An interim frame on an invoke's connection: { id, progress: { fraction, message } }.
        /// A frame carrying this field is never the reply; the reader keeps reading.</summary>
        public const string Progress = "progress";
        public const string ProgressFraction = "fraction";
        public const string ProgressMessage = "message";

        // "result" / "cancel" reply fields
        public const string JobStatus = "status";
        public const string JobCommand = "command";
        public const string JobSeconds = "seconds";
        public const string JobResult = "result";
        public const string JobError = "error";
        public const string Cancelled = "cancelled";

        /// <summary>What a stored call is doing, for the "result" reply. Closed set, like the codes.</summary>
        public static class JobStates
        {
            public const string Running = "running";
            public const string Done = "done";
            public const string Failed = "failed";
            public const string Cancelled = "cancelled";
            /// <summary>No call by that id: never seen, or older than the retention window.</summary>
            public const string Unknown = "unknown";
        }

        // "list" result fields
        public const string Commands = "commands";
        public const string Name = "name";
        public const string SourceField = "source";
        public const string Description = "description";
        public const string ReadOnly = "readOnly";
        public const string Destructive = "destructive";
        public const string InputSchema = "inputSchema";

        /// <summary>Schema of what the command RETURNS, from RevitCommandAttribute.OutputType. An empty
        /// object schema means the command has not declared one yet (most have not — see #89).
        /// NOTE for whoever wires this into the MCP tool definition: declaring a tool's outputSchema
        /// obliges the server to return structuredContent conforming to it, so the two changes go
        /// together or not at all.</summary>
        public const string OutputSchema = "outputSchema";

        // Error object fields
        public const string ErrorCode = "code";
        public const string ErrorMessage = "message";

        /// <summary>What to DO about it, when there is something to do. Omitted rather than filled with a
        /// restatement of the message — a hint that adds nothing trains a reader to skip hints.</summary>
        public const string ErrorHint = "hint";

        /// <summary>
        /// The closed set of error codes. Closed on purpose: a caller can only branch on values it knows,
        /// so a new code is a deliberate addition here, not a string invented at a throw site.
        /// </summary>
        public static class Codes
        {
            /// <summary>Missing or wrong bridge token. Not retryable without reconfiguring the client.</summary>
            public const string Unauthorized = "unauthorized";

            /// <summary>The payload did not match the command's published inputSchema. Retryable by the
            /// caller alone: fix the arguments, call again.</summary>
            public const string InvalidArguments = "invalid_arguments";

            /// <summary>No command by that name. Retryable after tools/list.</summary>
            public const string UnknownCommand = "unknown_command";

            /// <summary>The command exists but this transport may not call it. Not retryable as-is.</summary>
            public const string NotAvailable = "not_available";

            /// <summary>The command ran and threw. Whether it is retryable depends on the message.</summary>
            public const string CommandFailed = "command_failed";

            /// <summary>The call was cancelled — by the caller or by shutdown.</summary>
            public const string Cancelled = "cancelled";

            /// <summary>Minted client-side: Revit did not answer within the invoke deadline. Retryable
            /// once it goes idle, which GetQueueStatus can report.</summary>
            public const string Timeout = "timeout";

            /// <summary>Minted client-side: the bridge could not be reached at all. Revit is not running,
            /// or its MCP server is off.</summary>
            public const string RevitUnreachable = "revit_unreachable";
        }
    }
}
