namespace AnalyseTool.Mcp
{
    /// <summary>
    /// Wire contract of the localhost TCP bridge between the two halves of the MCP subsystem:
    /// AnalyseTool.Mcp.exe (out-of-process, System.Text.Json) and AnalyseTool.Mcp.Bridge
    /// (in-Revit, Newtonsoft). The file is COMPILED INTO BOTH projects (linked in the exe's
    /// csproj), so renaming a field breaks the build instead of silently breaking the wire.
    ///
    /// Shapes:
    ///   request  { id, token, type: "invoke"|"list", command?, payload? }
    ///   response { id, result } | { id, error }
    ///   list result: { commands: [ { name, source, description, readOnly, destructive,
    ///                                inputSchema, outputSchema } ] }
    ///
    /// Every request carries the session token. Binding to 127.0.0.1 keeps the browser and the network
    /// out, but it does not keep out other processes running as the same user — and this bridge drives
    /// Revit. The token is generated by the host, stored in mcp.json (a user-only file) and handed to
    /// the exe on its command line by the config snippet Settings generates.
    /// </summary>
    internal static class McpWire
    {
        public const int DefaultPort = 17890;

        // Envelope fields
        public const string Id = "id";
        public const string Token = "token";
        public const string Type = "type";
        public const string Command = "command";
        public const string Payload = "payload";
        public const string Result = "result";
        public const string Error = "error";

        // Request types
        public const string TypeInvoke = "invoke";
        public const string TypeList = "list";

        // "list" result fields
        public const string Commands = "commands";
        public const string Name = "name";
        public const string SourceField = "source";
        public const string Description = "description";
        public const string ReadOnly = "readOnly";
        public const string Destructive = "destructive";
        public const string InputSchema = "inputSchema";

        /// <summary>Schema of what the command RETURNS, from RevitCommandAttribute.OutputType. An empty
        /// object schema means the command has not declared one yet (most have not — see #89).
        /// NOTE for whoever wires this into the MCP tool definition: declaring a tool's outputSchema
        /// obliges the server to return structuredContent conforming to it, so the two changes go
        /// together or not at all.</summary>
        public const string OutputSchema = "outputSchema";
    }
}
