namespace AnalyseTool.Mcp
{
    /// <summary>
    /// Wire contract of the localhost TCP bridge between the two halves of the MCP subsystem:
    /// AnalyseTool.Mcp.exe (out-of-process, System.Text.Json) and AnalyseTool.Mcp.Bridge
    /// (in-Revit, Newtonsoft). The file is COMPILED INTO BOTH projects (linked in the exe's
    /// csproj), so renaming a field breaks the build instead of silently breaking the wire.
    ///
    /// Shapes:
    ///   request  { id, token, type: "invoke"|"list", command?, payload? }
    ///   response { id, result } | { id, error: { code, message, hint? } }
    ///   list result: { commands: [ { name, source, description, readOnly, destructive,
    ///                                inputSchema, outputSchema } ] }
    ///
    /// The error is an OBJECT so a caller can branch on <c>code</c> instead of matching prose — an agent
    /// deciding between "fix the arguments and retry" and "wait for Revit" should not be doing string
    /// comparison on a sentence that may be reworded. Both halves ship from the same build, so the shape
    /// cannot skew; the reader still accepts a bare string, because tolerating the older form costs one
    /// line and turns a hypothetical mismatch into a readable message rather than a crash.
    ///
    /// Every request carries the session token. Binding to 127.0.0.1 keeps the browser and the network
    /// out, but it does not keep out other processes running as the same user — and this bridge drives
    /// Revit. The token is generated by the host, stored in mcp.json (a user-only file) and handed to
    /// the exe on its command line by the config snippet Settings generates.
    /// </summary>
    internal static class McpWire
    {
        public const int DefaultPort = 17890;

        // Envelope fields
        public const string Id = "id";
        public const string Token = "token";
        public const string Type = "type";
        public const string Command = "command";
        public const string Payload = "payload";
        public const string Result = "result";
        public const string Error = "error";

        // Request types
        public const string TypeInvoke = "invoke";
        public const string TypeList = "list";
        /// <summary>Asks for nothing but the catalog stamp — the cheapest possible request, for a client
        /// polling "did the tool set change while I was not looking".</summary>
        public const string TypeVersion = "version";

        /// <summary>Stamped onto EVERY reply (result and error alike): an opaque string that changes
        /// whenever the set of commands an AI may call changes — extensions reloaded, the C# switch
        /// flipped. The exe compares it with the one it listed under and, on a difference, re-lists and
        /// tells the client (tools/list_changed). It is the only signal that crosses the wire in the
        /// server→client direction, and it rides on replies because the bridge cannot initiate.</summary>
        public const string Catalog = "catalog";

        // "list" result fields
        public const string Commands = "commands";
        public const string Name = "name";
        public const string SourceField = "source";
        public const string Description = "description";
        public const string ReadOnly = "readOnly";
        public const string Destructive = "destructive";
        public const string InputSchema = "inputSchema";

        /// <summary>Schema of what the command RETURNS, from RevitCommandAttribute.OutputType. An empty
        /// object schema means the command has not declared one yet (most have not — see #89).
        /// NOTE for whoever wires this into the MCP tool definition: declaring a tool's outputSchema
        /// obliges the server to return structuredContent conforming to it, so the two changes go
        /// together or not at all.</summary>
        public const string OutputSchema = "outputSchema";

        // Error object fields
        public const string ErrorCode = "code";
        public const string ErrorMessage = "message";

        /// <summary>What to DO about it, when there is something to do. Omitted rather than filled with a
        /// restatement of the message — a hint that adds nothing trains a reader to skip hints.</summary>
        public const string ErrorHint = "hint";

        /// <summary>
        /// The closed set of error codes. Closed on purpose: a caller can only branch on values it knows,
        /// so a new code is a deliberate addition here, not a string invented at a throw site.
        /// </summary>
        public static class Codes
        {
            /// <summary>Missing or wrong bridge token. Not retryable without reconfiguring the client.</summary>
            public const string Unauthorized = "unauthorized";

            /// <summary>The payload did not match the command's published inputSchema. Retryable by the
            /// caller alone: fix the arguments, call again.</summary>
            public const string InvalidArguments = "invalid_arguments";

            /// <summary>No command by that name. Retryable after tools/list.</summary>
            public const string UnknownCommand = "unknown_command";

            /// <summary>The command exists but this transport may not call it. Not retryable as-is.</summary>
            public const string NotAvailable = "not_available";

            /// <summary>The command ran and threw. Whether it is retryable depends on the message.</summary>
            public const string CommandFailed = "command_failed";

            /// <summary>The call was cancelled — by the caller or by shutdown.</summary>
            public const string Cancelled = "cancelled";

            /// <summary>Minted client-side: Revit did not answer within the invoke deadline. Retryable
            /// once it goes idle, which GetQueueStatus can report.</summary>
            public const string Timeout = "timeout";

            /// <summary>Minted client-side: the bridge could not be reached at all. Revit is not running,
            /// or its MCP server is off.</summary>
            public const string RevitUnreachable = "revit_unreachable";
        }
    }
}
