name: Publish Release

on:
  push:
    branches: [ "main" ]


jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Install WiX
        run: dotnet tool install --global wix --version 4.*

      - name: Run NUKE Publish
        run: ./build.cmd PublishGitHub
        shell: pwsh
        env:
          PUBLISH_VERSION: ${{ github.ref_name }}    
