name: Publish Release

on:
  push:
    branches: [ "main" ]


jobs:
  windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Install WiX Toolset 3.14
        run: |
          curl -L -o wix.zip https://wixtoolset.org/downloads/v3.14.0.5722/wix314-binaries.zip
          tar -xf wix.zip -C $env:ProgramFiles
          echo "$env:ProgramFiles\wix314-binaries" >> $env:GITHUB_PATH
        shell: pwsh

      - name: Run NUKE Publish
        run: ./build.cmd PublishGitHub
        shell: pwsh
        env:
          PUBLISH_VERSION: ${{ github.ref_name }}    
